defaults: &defaults
#production id and secret  
  instagram_client_id: "8b6e101c123d49f7ae9eb49152e4e7f4"
  instagram_client_secret: "83460f7c224648f5b99b9471d17749d0"
  instagram_access_token: "1521113753.8b6e101.d13ffae8e3e44d58b2b202f69f097b5c"
  default_image_search_tag: "shaw150"
  # If populated, the next three fields will appear at the end of page titles as "application_name - division_name - organization_name"
  application_name: "#shaw150"
  division_name: "Department of Humanities"
  division_url: "http://www.shawu.edu/Academics/Department_of_Humanities.aspx"
  organization_name: "Shaw University"
  meta_description: "Check out this image of Shaw University taken during the university's 150th year"
  base_image_file_dir: "tmp/harvested"
  donor_agreement_text: "Shaw University wants your photo! In celebration of the 150th year, Shaw University wants to archive all photos taken with the shaw150 Instagram tag. By consenting, you allow Shaw University to preserve and reproduce your photo. If you would like to opt out, please reply to this comment with 'opt out'."
  contact_email: "ddighton@shawu.edu"
  feed_description: "Shaw 150 pictures"
  # Uncomment to enable Google Analytics tracking
  google_analytics_tracker: "UA-55496633-1"

development:
  <<: *defaults
  # Add or override config options here

test:
  <<: *defaults
  # Add or override config options here

staging:
  <<: *defaults
  # Add or override config options here

production:
  <<: *defaults
  # Add or override config options here
